import os
import sys
from datetime import datetime

# Adjust Python path to import app modules
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sqlalchemy.orm import Session
from app.database.session import SessionLocal
from app.models.movie import *
from app.api import deps
from app.core.logging import setup_logging

def check_diagnostics():
    setup_logging()
    print("=== STARTING DIAGNOSTICS CHECK (ENHANCED METADATA) ===")
    
    # 1. PostgreSQL Check
    print("\n--- 1. PostgreSQL Relational Database ---")
    db: Session = SessionLocal()
    try:
        movies = db.query(Movie).all()
        print(f"Total Movies: {len(movies)}")
        for m in movies:
            print(f"- Title: {m.title} (ID: {m.tmdb_id}, Year: {m.release_year})")
            print(f"  Movie Metadata:")
            print(f"    - Source: {m.source}")
            print(f"    - Confidence: {m.confidence_score}")
            print(f"    - Generated By: {m.generated_by}")
            print(f"    - Generated At: {m.generated_at}")
            
            # Check scene metadata
            scenes = db.query(Scene).filter(Scene.movie_id == m.id).all()
            print(f"  Scenes count: {len(scenes)}")
            for s in scenes[:2]:
                print(f"    - Scene Index: {s.scene_index}")
                print(f"      - Source: {s.source}")
                print(f"      - Confidence: {s.confidence_score}")
                print(f"      - Generated By: {s.generated_by}")
                print(f"      - Generated At: {s.generated_at}")
                
                # Check dialogue metadata
                dials = db.query(Dialogue).filter(Dialogue.scene_id == s.id).all()
                print(f"      - Dialogues count: {len(dials)}")
                for d in dials[:1]:
                    print(f"        - Speaker: {d.speaker}")
                    print(f"        - Source: {d.source}")
                    print(f"        - Confidence: {d.confidence_score}")
                    print(f"        - Generated By: {d.generated_by}")
                    print(f"        - Generated At: {d.generated_at}")
            
            # Check cast metadata
            cast = db.query(MovieCast).filter(MovieCast.movie_id == m.id).all()
            print(f"  Cast count: {len(cast)}")
            for c in cast[:2]:
                print(f"    - Character: {c.character_name}")
                print(f"      - Source: {c.source}")
                print(f"      - Confidence: {c.confidence_score}")
                print(f"      - Generated By: {c.generated_by}")
                print(f"      - Generated At: {c.generated_at}")
                
    except Exception as e:
        print(f"PostgreSQL Query failed: {e}")
    finally:
        db.close()

    # 2. Neo4j Check
    print("\n--- 2. Neo4j Knowledge Graph ---")
    try:
        graph = deps.get_knowledge_graph()
        total_nodes = graph.execute_query("MATCH (n) RETURN count(n) as count")[0].get("count", 0)
        total_rels = graph.execute_query("MATCH ()-[r]->() RETURN count(r) as count")[0].get("count", 0)
        print(f"Total Nodes: {total_nodes}")
        print(f"Total Relationships: {total_rels}")
    except Exception as e:
        print(f"Neo4j Query failed: {e}")

    # 3. ChromaDB Check
    print("\n--- 3. ChromaDB Vector Database ---")
    try:
        vector = deps.get_vector_store()
        collections = ["movie_overviews", "characters", "scenes", "dialogues", "themes", "memory_cues", "visual_cues"]
        print("Vector metadata highlights by collection:")
        for col in collections:
            count = vector.count(collection_name=col)
            print(f"  - {col} count: {count}")
            if count > 0:
                # Query one document metadata to inspect fields
                collection = vector.client.get_collection(col)
                res = collection.get(limit=1)
                if res and res.get("metadatas"):
                    meta = res.get("metadatas")[0]
                    print(f"    Sample Metadata fields:")
                    print(f"      - embedding_model: {meta.get('embedding_model')}")
                    print(f"      - embedding_version: {meta.get('embedding_version')}")
                    print(f"      - source_provider: {meta.get('source_provider')}")
                    print(f"      - generated_at: {meta.get('generated_at')}")
                    print(f"      - source: {meta.get('source')}")
                    print(f"      - confidence_score: {meta.get('confidence_score')}")
    except Exception as e:
        print(f"ChromaDB Query failed: {e}")

    print("\n=== DIAGNOSTICS CHECK COMPLETE ===")

if __name__ == "__main__":
    check_diagnostics()
