"""expand_movie_ontology

Revision ID: 17b6ad544515
Revises: 8eb89baa0093
Create Date: 2026-07-14 17:51:44.363562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17b6ad544515'
down_revision: Union[str, Sequence[str], None] = '8eb89baa0093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emotions_id'), 'emotions', ['id'], unique=False)
    op.create_index(op.f('ix_emotions_name'), 'emotions', ['name'], unique=True)
    op.create_table('franchises',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_franchises_id'), 'franchises', ['id'], unique=False)
    op.create_index(op.f('ix_franchises_name'), 'franchises', ['name'], unique=True)
    op.create_table('moods',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moods_id'), 'moods', ['id'], unique=False)
    op.create_index(op.f('ix_moods_name'), 'moods', ['name'], unique=True)
    op.create_table('streaming_providers',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('availability', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streaming_providers_id'), 'streaming_providers', ['id'], unique=False)
    op.create_index(op.f('ix_streaming_providers_name'), 'streaming_providers', ['name'], unique=False)
    op.create_index(op.f('ix_streaming_providers_region'), 'streaming_providers', ['region'], unique=False)
    op.create_table('studios',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studios_id'), 'studios', ['id'], unique=False)
    op.create_index(op.f('ix_studios_name'), 'studios', ['name'], unique=True)
    op.create_table('themes',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_themes_id'), 'themes', ['id'], unique=False)
    op.create_index(op.f('ix_themes_name'), 'themes', ['name'], unique=True)
    op.create_table('awards',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('winner', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_awards_id'), 'awards', ['id'], unique=False)
    op.create_table('memory_cues',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_cues_id'), 'memory_cues', ['id'], unique=False)
    op.create_table('movie_conflicts',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_conflicts_id'), 'movie_conflicts', ['id'], unique=False)
    op.create_table('movie_emotions',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('emotion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['emotion_id'], ['emotions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'emotion_id')
    )
    op.create_table('movie_moods',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('mood_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mood_id'], ['moods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'mood_id')
    )
    op.create_table('movie_relationships',
    sa.Column('from_movie_id', sa.Integer(), nullable=False),
    sa.Column('to_movie_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('from_movie_id', 'to_movie_id', 'id')
    )
    op.create_index(op.f('ix_movie_relationships_id'), 'movie_relationships', ['id'], unique=False)
    op.create_table('movie_streaming_providers',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['streaming_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'provider_id')
    )
    op.create_table('movie_studios',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'studio_id')
    )
    op.create_table('movie_subplots',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_subplots_id'), 'movie_subplots', ['id'], unique=False)
    op.create_table('movie_themes',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'theme_id')
    )
    op.create_table('movie_twists',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_twists_id'), 'movie_twists', ['id'], unique=False)
    op.create_table('music',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('track_name', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_music_id'), 'music', ['id'], unique=False)
    op.create_table('reviews',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('critic_name', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_table('scenes',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('scene_index', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('importance', sa.Text(), nullable=True),
    sa.Column('scene_type', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenes_id'), 'scenes', ['id'], unique=False)
    op.create_table('visual_cues',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cue_type', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visual_cues_id'), 'visual_cues', ['id'], unique=False)
    op.create_table('dialogues',
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(length=255), nullable=False),
    sa.Column('listener', sa.String(length=255), nullable=True),
    sa.Column('dialogue_text', sa.Text(), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=True),
    sa.Column('emotional_tone', sa.String(length=100), nullable=True),
    sa.Column('subtext', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialogues_id'), 'dialogues', ['id'], unique=False)
    op.add_column('movie_cast', sa.Column('aliases', sa.JSON(), nullable=True))
    op.add_column('movie_cast', sa.Column('biography', sa.Text(), nullable=True))
    op.add_column('movie_cast', sa.Column('importance', sa.String(length=50), nullable=True))
    op.add_column('movie_cast', sa.Column('relationships', sa.JSON(), nullable=True))
    op.add_column('movie_cast', sa.Column('personality_traits', sa.JSON(), nullable=True))
    op.add_column('movie_cast', sa.Column('motivations', sa.JSON(), nullable=True))
    op.add_column('movie_cast', sa.Column('arc', sa.Text(), nullable=True))
    op.add_column('movies', sa.Column('imdb_id', sa.String(length=50), nullable=True))
    op.add_column('movies', sa.Column('wikidata_id', sa.String(length=50), nullable=True))
    op.add_column('movies', sa.Column('tvdb_id', sa.String(length=50), nullable=True))
    op.add_column('movies', sa.Column('original_title', sa.String(length=255), nullable=True))
    op.add_column('movies', sa.Column('release_date', sa.Date(), nullable=True))
    op.add_column('movies', sa.Column('budget', sa.BigInteger(), nullable=True))
    op.add_column('movies', sa.Column('revenue', sa.BigInteger(), nullable=True))
    op.add_column('movies', sa.Column('tagline', sa.Text(), nullable=True))
    op.add_column('movies', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('movies', sa.Column('adult', sa.Boolean(), nullable=True))
    op.add_column('movies', sa.Column('popularity', sa.Float(), nullable=True))
    op.add_column('movies', sa.Column('vote_average', sa.Float(), nullable=True))
    op.add_column('movies', sa.Column('vote_count', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('plot', sa.Text(), nullable=True))
    op.add_column('movies', sa.Column('plot_summary', sa.Text(), nullable=True))
    op.add_column('movies', sa.Column('story_arc', sa.Text(), nullable=True))
    op.add_column('movies', sa.Column('beginning', sa.Text(), nullable=True))
    op.add_column('movies', sa.Column('middle', sa.Text(), nullable=True))
    op.add_column('movies', sa.Column('climax', sa.Text(), nullable=True))
    op.add_column('movies', sa.Column('ending', sa.Text(), nullable=True))
    op.add_column('movies', sa.Column('ending_type', sa.String(length=100), nullable=True))
    op.add_column('movies', sa.Column('timeline', sa.Text(), nullable=True))
    op.add_column('movies', sa.Column('last_synced_at', sa.DateTime(), nullable=True))
    op.add_column('movies', sa.Column('franchise_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_movies_imdb_id'), 'movies', ['imdb_id'], unique=False)
    op.create_index(op.f('ix_movies_tvdb_id'), 'movies', ['tvdb_id'], unique=False)
    op.create_index(op.f('ix_movies_wikidata_id'), 'movies', ['wikidata_id'], unique=False)
    op.create_foreign_key(None, 'movies', 'franchises', ['franchise_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.drop_index(op.f('ix_movies_wikidata_id'), table_name='movies')
    op.drop_index(op.f('ix_movies_tvdb_id'), table_name='movies')
    op.drop_index(op.f('ix_movies_imdb_id'), table_name='movies')
    op.drop_column('movies', 'franchise_id')
    op.drop_column('movies', 'last_synced_at')
    op.drop_column('movies', 'timeline')
    op.drop_column('movies', 'ending_type')
    op.drop_column('movies', 'ending')
    op.drop_column('movies', 'climax')
    op.drop_column('movies', 'middle')
    op.drop_column('movies', 'beginning')
    op.drop_column('movies', 'story_arc')
    op.drop_column('movies', 'plot_summary')
    op.drop_column('movies', 'plot')
    op.drop_column('movies', 'vote_count')
    op.drop_column('movies', 'vote_average')
    op.drop_column('movies', 'popularity')
    op.drop_column('movies', 'adult')
    op.drop_column('movies', 'status')
    op.drop_column('movies', 'tagline')
    op.drop_column('movies', 'revenue')
    op.drop_column('movies', 'budget')
    op.drop_column('movies', 'release_date')
    op.drop_column('movies', 'original_title')
    op.drop_column('movies', 'tvdb_id')
    op.drop_column('movies', 'wikidata_id')
    op.drop_column('movies', 'imdb_id')
    op.drop_column('movie_cast', 'arc')
    op.drop_column('movie_cast', 'motivations')
    op.drop_column('movie_cast', 'personality_traits')
    op.drop_column('movie_cast', 'relationships')
    op.drop_column('movie_cast', 'importance')
    op.drop_column('movie_cast', 'biography')
    op.drop_column('movie_cast', 'aliases')
    op.drop_index(op.f('ix_dialogues_id'), table_name='dialogues')
    op.drop_table('dialogues')
    op.drop_index(op.f('ix_visual_cues_id'), table_name='visual_cues')
    op.drop_table('visual_cues')
    op.drop_index(op.f('ix_scenes_id'), table_name='scenes')
    op.drop_table('scenes')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_music_id'), table_name='music')
    op.drop_table('music')
    op.drop_index(op.f('ix_movie_twists_id'), table_name='movie_twists')
    op.drop_table('movie_twists')
    op.drop_table('movie_themes')
    op.drop_index(op.f('ix_movie_subplots_id'), table_name='movie_subplots')
    op.drop_table('movie_subplots')
    op.drop_table('movie_studios')
    op.drop_table('movie_streaming_providers')
    op.drop_index(op.f('ix_movie_relationships_id'), table_name='movie_relationships')
    op.drop_table('movie_relationships')
    op.drop_table('movie_moods')
    op.drop_table('movie_emotions')
    op.drop_index(op.f('ix_movie_conflicts_id'), table_name='movie_conflicts')
    op.drop_table('movie_conflicts')
    op.drop_index(op.f('ix_memory_cues_id'), table_name='memory_cues')
    op.drop_table('memory_cues')
    op.drop_index(op.f('ix_awards_id'), table_name='awards')
    op.drop_table('awards')
    op.drop_index(op.f('ix_themes_name'), table_name='themes')
    op.drop_index(op.f('ix_themes_id'), table_name='themes')
    op.drop_table('themes')
    op.drop_index(op.f('ix_studios_name'), table_name='studios')
    op.drop_index(op.f('ix_studios_id'), table_name='studios')
    op.drop_table('studios')
    op.drop_index(op.f('ix_streaming_providers_region'), table_name='streaming_providers')
    op.drop_index(op.f('ix_streaming_providers_name'), table_name='streaming_providers')
    op.drop_index(op.f('ix_streaming_providers_id'), table_name='streaming_providers')
    op.drop_table('streaming_providers')
    op.drop_index(op.f('ix_moods_name'), table_name='moods')
    op.drop_index(op.f('ix_moods_id'), table_name='moods')
    op.drop_table('moods')
    op.drop_index(op.f('ix_franchises_name'), table_name='franchises')
    op.drop_index(op.f('ix_franchises_id'), table_name='franchises')
    op.drop_table('franchises')
    op.drop_index(op.f('ix_emotions_name'), table_name='emotions')
    op.drop_index(op.f('ix_emotions_id'), table_name='emotions')
    op.drop_table('emotions')
    # ### end Alembic commands ###
