"""add_metadata_and_confidence_columns

Revision ID: ed79141a0d00
Revises: 17b6ad544515
Create Date: 2026-07-14 18:22:10.420056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed79141a0d00'
down_revision: Union[str, Sequence[str], None] = '17b6ad544515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dialogues', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('dialogues', sa.Column('generated_by', sa.String(length=100), nullable=True))
    op.add_column('dialogues', sa.Column('generated_at', sa.DateTime(), nullable=True))
    op.add_column('dialogues', sa.Column('source', sa.String(length=50), nullable=True))
    op.add_column('memory_cues', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('memory_cues', sa.Column('generated_by', sa.String(length=100), nullable=True))
    op.add_column('memory_cues', sa.Column('generated_at', sa.DateTime(), nullable=True))
    op.add_column('memory_cues', sa.Column('source', sa.String(length=50), nullable=True))
    op.add_column('movie_cast', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('movie_cast', sa.Column('generated_by', sa.String(length=100), nullable=True))
    op.add_column('movie_cast', sa.Column('generated_at', sa.DateTime(), nullable=True))
    op.add_column('movie_cast', sa.Column('source', sa.String(length=50), nullable=True))
    op.add_column('movie_conflicts', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('movie_conflicts', sa.Column('generated_by', sa.String(length=100), nullable=True))
    op.add_column('movie_conflicts', sa.Column('generated_at', sa.DateTime(), nullable=True))
    op.add_column('movie_conflicts', sa.Column('source', sa.String(length=50), nullable=True))
    op.add_column('movie_subplots', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('movie_subplots', sa.Column('generated_by', sa.String(length=100), nullable=True))
    op.add_column('movie_subplots', sa.Column('generated_at', sa.DateTime(), nullable=True))
    op.add_column('movie_subplots', sa.Column('source', sa.String(length=50), nullable=True))
    op.add_column('movie_twists', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('movie_twists', sa.Column('generated_by', sa.String(length=100), nullable=True))
    op.add_column('movie_twists', sa.Column('generated_at', sa.DateTime(), nullable=True))
    op.add_column('movie_twists', sa.Column('source', sa.String(length=50), nullable=True))
    op.add_column('movies', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('movies', sa.Column('generated_by', sa.String(length=100), nullable=True))
    op.add_column('movies', sa.Column('generated_at', sa.DateTime(), nullable=True))
    op.add_column('movies', sa.Column('source', sa.String(length=50), nullable=True))
    op.add_column('scenes', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('scenes', sa.Column('generated_by', sa.String(length=100), nullable=True))
    op.add_column('scenes', sa.Column('generated_at', sa.DateTime(), nullable=True))
    op.add_column('scenes', sa.Column('source', sa.String(length=50), nullable=True))
    op.add_column('visual_cues', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('visual_cues', sa.Column('generated_by', sa.String(length=100), nullable=True))
    op.add_column('visual_cues', sa.Column('generated_at', sa.DateTime(), nullable=True))
    op.add_column('visual_cues', sa.Column('source', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visual_cues', 'source')
    op.drop_column('visual_cues', 'generated_at')
    op.drop_column('visual_cues', 'generated_by')
    op.drop_column('visual_cues', 'confidence_score')
    op.drop_column('scenes', 'source')
    op.drop_column('scenes', 'generated_at')
    op.drop_column('scenes', 'generated_by')
    op.drop_column('scenes', 'confidence_score')
    op.drop_column('movies', 'source')
    op.drop_column('movies', 'generated_at')
    op.drop_column('movies', 'generated_by')
    op.drop_column('movies', 'confidence_score')
    op.drop_column('movie_twists', 'source')
    op.drop_column('movie_twists', 'generated_at')
    op.drop_column('movie_twists', 'generated_by')
    op.drop_column('movie_twists', 'confidence_score')
    op.drop_column('movie_subplots', 'source')
    op.drop_column('movie_subplots', 'generated_at')
    op.drop_column('movie_subplots', 'generated_by')
    op.drop_column('movie_subplots', 'confidence_score')
    op.drop_column('movie_conflicts', 'source')
    op.drop_column('movie_conflicts', 'generated_at')
    op.drop_column('movie_conflicts', 'generated_by')
    op.drop_column('movie_conflicts', 'confidence_score')
    op.drop_column('movie_cast', 'source')
    op.drop_column('movie_cast', 'generated_at')
    op.drop_column('movie_cast', 'generated_by')
    op.drop_column('movie_cast', 'confidence_score')
    op.drop_column('memory_cues', 'source')
    op.drop_column('memory_cues', 'generated_at')
    op.drop_column('memory_cues', 'generated_by')
    op.drop_column('memory_cues', 'confidence_score')
    op.drop_column('dialogues', 'source')
    op.drop_column('dialogues', 'generated_at')
    op.drop_column('dialogues', 'generated_by')
    op.drop_column('dialogues', 'confidence_score')
    # ### end Alembic commands ###
